cuda_dir = getenv('CUDA_PATH');
cublas_dir = [cuda_dir,filesep,'lib',filesep,'x64'];

compile_ff = true;
compile_nf = true;
compile_refocus = true;

% delete(['bin',filesep,'*.*']);
if(compile_nf)
    headers = ...
    { ...
        ['-I cuda',filesep,'common',filesep,'headers'], ...
        ['-I cuda',filesep,'common',filesep,'headers',filesep,'math'], ...
        ['-I cuda',filesep,'common',filesep,'headers',filesep,'scattering'], ...
        ['-I cuda',filesep,'common',filesep,'kernels',filesep,'math'], ...
        ['-I cuda',filesep,'nf',filesep,'interface'], ...
        ['-I cuda',filesep,'nf',filesep,'internal',filesep,'headers'] ...
    };

    objects_list = { ...
        ['cuda',filesep,'common',filesep,'kernels',filesep,'scattering',filesep,'sampleScattering.cu'] , ...
        ['cuda',filesep,'common',filesep,'kernels',filesep,'scattering',filesep,'hg_scattering.cu'], ...
        ['cuda',filesep,'common',filesep,'kernels',filesep,'scattering',filesep,'random_scattering.cu'], ...
        ['cuda',filesep,'common',filesep,'kernels',filesep,'scattering',filesep,'tabulated_scattering.cu'], ...
        ['cuda',filesep,'common',filesep,'cpp',filesep,'standardC.cpp'] , ...
        ['cuda',filesep,'common',filesep,'kernels',filesep,'math',filesep,'globalMathKernels.cu'], ...
        ['cuda',filesep,'nf',filesep,'internal',filesep,'nf_run.cu'] , ...
        ['cuda',filesep,'nf',filesep,'internal',filesep,'kernels',filesep,'sampling',filesep,'samplingPreprocess.cu'], ...
        ['cuda',filesep,'nf',filesep,'internal',filesep,'kernels',filesep,'sampling',filesep,'sampleDirection.cu'], ...
        ['cuda',filesep,'nf',filesep,'internal',filesep,'kernels',filesep,'sampling',filesep,'samplePosition.cu'], ...
        ['cuda',filesep,'nf',filesep,'internal',filesep,'kernels',filesep,'scattering',filesep,'multipleScattering.cu'], ...
        ['cuda',filesep,'nf',filesep,'internal',filesep,'kernels',filesep,'scattering',filesep,'singleScattering.cu'], ...
        ['cuda',filesep,'nf',filesep,'internal',filesep,'nf_calc_size.cpp'] , ...
    };

    mexcuda( ...
        '-dynamic',['mex',filesep,'nf_mex.cpp'], objects_list, headers, ...
        '-outdir', ['mex',filesep,'bin'],'-R2018a');
end

if(compile_ff)
    headers = ...
    { ...
        ['-I cuda',filesep,'common',filesep,'headers'], ...
        ['-I cuda',filesep,'common',filesep,'headers',filesep,'math'], ...
        ['-I cuda',filesep,'common',filesep,'headers',filesep,'scattering'], ...
        ['-I cuda',filesep,'common',filesep,'kernels',filesep,'math'], ...
        ['-I cuda',filesep,'ff',filesep,'interface'], ...
        ['-I cuda',filesep,'ff',filesep,'internal',filesep,'headers'] ...
    };

    objects_list = { ...
        ['cuda',filesep,'common',filesep,'kernels',filesep,'scattering',filesep,'sampleScattering.cu'] , ...
        ['cuda',filesep,'common',filesep,'kernels',filesep,'scattering',filesep,'hg_scattering.cu'], ...
        ['cuda',filesep,'common',filesep,'kernels',filesep,'scattering',filesep,'random_scattering.cu'], ...
        ['cuda',filesep,'common',filesep,'kernels',filesep,'scattering',filesep,'tabulated_scattering.cu'], ...
        ['cuda',filesep,'common',filesep,'cpp',filesep,'standardC.cpp'] , ...
        ['cuda',filesep,'common',filesep,'kernels',filesep,'math',filesep,'globalMathKernels.cu'], ...
        ['cuda',filesep,'ff',filesep,'internal',filesep,'ff_run.cu'] , ...
        ['cuda',filesep,'ff',filesep,'internal',filesep,'kernels',filesep,'sampling',filesep,'samplePreprocess.cu'], ...
        ['cuda',filesep,'ff',filesep,'internal',filesep,'kernels',filesep,'sampling',filesep,'sampleDirection.cu'], ...
        ['cuda',filesep,'ff',filesep,'internal',filesep,'kernels',filesep,'sampling',filesep,'samplePosition.cu'], ...
        ['cuda',filesep,'ff',filesep,'internal',filesep,'kernels',filesep,'scattering',filesep,'multipleScattering.cu'], ...
        ['cuda',filesep,'ff',filesep,'internal',filesep,'kernels',filesep,'scattering',filesep,'singleScattering.cu'], ...
        ['cuda',filesep,'ff',filesep,'internal',filesep,'ff_calc_size.cpp'] , ...
    };

    mexcuda( ...
        '-dynamic',['mex',filesep,'ff_mex.cpp'], objects_list, headers, ...
        '-outdir', ['mex',filesep,'bin'],'-R2018a');
end

if(compile_refocus)
    headers = ...
    { ...
        ['-I cuda',filesep,'common',filesep,'headers'], ...
        ['-I cuda',filesep,'common',filesep,'headers',filesep,'math'], ...
        ['-I cuda',filesep,'common',filesep,'headers',filesep,'scattering'], ...
        ['-I cuda',filesep,'common',filesep,'kernels',filesep,'math'], ...
        ['-I cuda',filesep,'refocus',filesep,'interface'], ...
        ['-I cuda',filesep,'refocus',filesep,'internal',filesep,'headers'] ...
    };

    objects_list = { ...
        ['cuda',filesep,'common',filesep,'kernels',filesep,'scattering',filesep,'sampleScattering.cu'] , ...
        ['cuda',filesep,'common',filesep,'kernels',filesep,'scattering',filesep,'hg_scattering.cu'], ...
        ['cuda',filesep,'common',filesep,'kernels',filesep,'scattering',filesep,'random_scattering.cu'], ...
        ['cuda',filesep,'common',filesep,'kernels',filesep,'scattering',filesep,'tabulated_scattering.cu'], ...
        ['cuda',filesep,'common',filesep,'cpp',filesep,'standardC.cpp'] , ...
        ['cuda',filesep,'common',filesep,'kernels',filesep,'math',filesep,'globalMathKernels.cu'], ...
        ['cuda',filesep,'common',filesep,'kernels',filesep,'math',filesep,'blasMatrix.cu'], ...
        ['cuda',filesep,'refocus',filesep,'internal',filesep,'refocus_run.cu'] , ...
        ['cuda',filesep,'refocus',filesep,'internal',filesep,'kernels',filesep,'refocus',filesep,'refocus_build.cu'], ...
        ['cuda',filesep,'refocus',filesep,'internal',filesep,'kernels',filesep,'sampling',filesep,'samplePosition.cu'], ...
        ['cuda',filesep,'refocus',filesep,'internal',filesep,'kernels',filesep,'sampling',filesep,'sampleDirection.cu'], ...
        ['cuda',filesep,'refocus',filesep,'internal',filesep,'kernels',filesep,'scattering',filesep,'singleScattering.cu'], ...
        ['cuda',filesep,'refocus',filesep,'internal',filesep,'kernels',filesep,'scattering',filesep,'multipleScattering.cu'], ...
        ['cuda',filesep,'refocus',filesep,'internal',filesep,'refocus_calc_size.cpp'] , ...
    };

    mexcuda( ...
        '-dynamic',['mex',filesep,'refocus_mex.cpp'], objects_list, headers, ['-L',cublas_dir], '-lcublas', ...
        '-outdir', ['mex',filesep,'bin'],'-R2018a');
end
